package com.swiggy.agileflow.notification.domain;

/** Categories of notifications generated by the platform. */
public enum NotificationType {
    ASSIGNMENT,
    MENTION,
    STATUS_CHANGE,
    WATCHER_UPDATE
}
